# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_remove_song_playlists'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='songs.Song', verbose_name='Songs'),
        ),
    ]
