# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170212_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='songs.Song', verbose_name='Songs'),
        ),
    ]
