# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_title',
            field=models.CharField(max_length=100, verbose_name='Album Title'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=100, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to=b'', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hiphop', 'HipHop'), ('jazz', 'Jazz'), ('classic', 'Classic')], max_length=50, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='logo',
            field=models.FileField(default='', upload_to=b'', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=100, verbose_name='Song Title'),
        ),
    ]
