# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('songs', '0005_song_fk_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='fk_playlist',
        ),
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(to='users.PlayList', verbose_name='PlayList'),
        ),
    ]
