# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20170205_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='', null=True, upload_to=b'', verbose_name='Audio File'),
        ),
    ]
