# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_remove_song_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='logo',
            field=models.FileField(blank=True, default='', null=True, upload_to=b'', verbose_name='Logo'),
        ),
    ]
